//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int Id { get; set; }
        public string NameRu { get; set; }
        public string NameAz { get; set; }
        public string NameEn { get; set; }
        public Nullable<int> Duration { get; set; }
        public string DescriptionRu { get; set; }
        public string DescriptionAz { get; set; }
        public string DescriptionEn { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
